stages:

  - stage: BuildServices

    pool:
      vmImages: ubuntu-latest

    jobs:
    - job: BuildDocker_SalesBookLB
      displayName: Build Docker Image for SalesBook.LB app
      steps:

      - task: Docker@2
        inputs:
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            $(Build.BuildId)
            latest